### ISSUE TITLE
not convergenced

### ISSUE THREAD

**Issue by tengshaofeng** [soloice/Chinese-Character-Recognition#2]
hi, i using a similarity data set as yours.

my data sets include:
             1)3755 chinese characters  which are generated by computer from 11 kinds of fonts such as    
                simsun(宋体).  
             2) 10 digits
all the characters are not handwriting, and about 500 samples for each class. 
and i am sure that i modify the code properly for input.
but when i  using your code to run on my dataset. it seems not convergenced like:

![image](https://cloud.githubusercontent.com/assets/9246739/24283564/92515860-10a1-11e7-85c0-461b35182f38.png)

why? can you give me some advise? thanks

**Comment by soloice** [comment]
This should be due to improper learning rate.

Here is my advice:

1. Be patient. Let the algorithm run for a longer time, i.e. 300~500 steps, you may see loss goes down. If the learning rate schedule is aggressive (kind of large),  the first few steps may wander but it'll go down later.

2. If loss still cannot get down, you could use a lower learning rate. Typically exponential decay is a good method: decay learning rate exponentially until you find a good initial learning rate.

**Comment by tengshaofeng** [comment]
thanks so much for your advise. it  convergenced  in a longer time.

**Comment by soloice** [comment]
Glad to hear that.
