### ISSUE TITLE
input images not divided by 255.0?

### ISSUE THREAD

**Issue by tengshaofeng** [soloice/Chinese-Character-Recognition#3]
hi, sorry to bother you again.
i have not seen dividing the input images by 255.0 before training.  does it mean that value of your stored images have already made between 0 and 1?  
does the function 'tf.image.convert_image_dtype(tf.image.decode_png(images_content, channels=1), tf.float32)' regurlize the input data to [0,1]?  but i print the batch_images , it is like this include negative number:
![image](https://cloud.githubusercontent.com/assets/9246739/24446628/c8499830-14a0-11e7-91a3-2667f8b75945.png)
so, i do not know it is  (x-mean)/std or  x/max(x)?

**Comment by soloice** [comment]
A nice catch. I'm not sure about this, either. 
I'll check it as soon as possible. Thanks for your code review.

**Comment by soloice** [comment]
Hi, it is like this:

- I use normal png pictures, so when I read images through `tf.image.decode_png(images_content, channels=1)`, I will get a tensor of dtype `tf.uint8` and the data range is [0, 255].
- After apply `tf.image.convert_image_dtype()` to it, the result will be normalized to [0, 1], i.e. `tf.image.convert_image_dtype(tf.image.decode_png(images_content, channels=1), tf.float32) = tf.image.decode_png(images_content, channels=1) / 255.0`.
- Furthermore, because I use some data augmentation methods to improve the performance of the model, including `tf.image.random_brightness(images, max_delta=0.3)`, which means if the `aug` parameter of function `DataIterator().input_pipeline()` is `True`, a random noise between [-0.3, 0.3] will be added to input images, thus inputs of the neural network might contain negative values.

Note that I also use `tf.image.random_contrast(images, 0.8, 1.2)` to scale the input images, the maximum value of an input image minus its minimum value can vary between [0.8, 1.2]. (**not always 1.0**!)


For the case you posted above, I believe this is what happened:

- After `tf.image.convert_image_dtype(tf.image.decode_png(images_content, channels=1), tf.float32)`, you get a normalized image, whose data range is between 0.0 and 1.0. 
- Then the algorithm chose a random delta within range [-max_delta, max_delta] to shift the image, i.e.: it chose delta=-0.23 and plus every pixel of the image by -0.23. After this step, the data range of the image is [0.0, 1.0] + (-0.23) = [-0.23, 0.77]. 
- Now the algorithm choose a random scaling factor within range [0.8, 1.2] to scale the image. To be precise, it chose 1.04, thus the data range of input image now is [-0.23, 0.77] * 1.04 = [-0.24, 0.80].

I hope this is clear enough. Sorry for my late reply.

**Comment by tengshaofeng** [comment]
thanks so much. so nice an answer.
